version: '2'
services:
  app:
    build: conda3-analytics/.
    mem_limit: 4G
    environment:
      DATABASE_URL: mysql2://root:pass@mysql:3306
      MYSQL_ROOT_PASSWORD: 'pass'
    ports:
      - '8888:8888'
    volumes:
      - ./mounts:/notebooks
    links:
      - mysql
    tty: true
  mysql:
    image: mysql:5.7.10
    hostname: dbserver
    environment:
      MYSQL_ROOT_PASSWORD: 'pass'
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
    driver: local
